cpp_build_test:
    image: nixos/nix
    stage: build
    script:
        - cd tp-workflow/cpp
        - nix-build

cpp_doc:
    image: alpine
    before_script:
        - apk add doxygen
    stage: build
    artifacts:
        untracked: true
    script:
        - cd tp-workflow/cpp
        - doxygen

pages:
    image: alpine
    stage: deploy
    dependencies: 
        - cpp_doc
    script:
        - mkdir -p public
        - cp -R tp-workflow/cpp/doc/html/* public/
    artifacts:
        paths:
            - public


